[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/openai/**"]

[functions."___netlify-server-handler"]
  timeout = 26

[[plugins]]
  package = "@netlify/plugin-nextjs"
